#!/usr/bin/env python3
"""Validate generated cued recall BIDS events against metainformation reference.

Compares events files generated by timed_events.py for cued recall sessions
against the pre-formatted reference files in sourcedata/metainformation/.

Validation checks:
  1. Row count match
  2. Exact match on categorical columns (trial_id, word, pairId, mmmId, trial_type)
  3. Numeric match within tolerance for timing columns (onset_actual, duration_actual)
  4. Exact match on response columns (resp, resp_RT)

Session mapping:
  Metainformation uses ses-01 to ses-15 (cued recall session number).
  BIDS output uses ses-04 to ses-18 (cued recall session + 3).

Usage:
    python validate.py [--subjects SUB1,SUB2,...] [--tolerance 0.01] [--verbose]
"""

import argparse
import os
import sys

import pandas as pd

from common import (
    BIDS_ROOT, METAINFO_DIR, CR_SESSION_OFFSET,
    bids_sub, bids_ses, bids_ses_cr, SUBJECT_NUMS,
)


TIMING_TOLERANCE = 0.01  # seconds


def find_metainfo_file(sub_num, cr_session, task, run):
    """Find the metainformation reference file for a given session/task/run.

    Metainformation uses ses-01 to ses-15 numbering (cued recall session).
    """
    sub = bids_sub(sub_num)
    ses = bids_ses(cr_session)  # metainfo uses cued recall session directly

    if task == "math":
        fname = f"{sub}_{ses}_task-{task}_run-01_events.tsv"
    else:
        fname = f"{sub}_{ses}_task-{task}_run-{run:02d}_events.tsv"

    path = os.path.join(METAINFO_DIR, sub, ses, fname)
    return path if os.path.exists(path) else None


def find_generated_file(sub_num, cr_session, task, run):
    """Find the generated BIDS events file for a given session/task/run.

    Generated files use BIDS ses-04 to ses-18 numbering.
    """
    sub = bids_sub(sub_num)
    ses = bids_ses_cr(cr_session)

    if task == "math":
        fname = f"{sub}_{ses}_task-{task}_events.tsv"
    else:
        fname = f"{sub}_{ses}_task-{task}_run-{run:02d}_events.tsv"

    path = os.path.join(BIDS_ROOT, sub, ses, "func", fname)
    return path if os.path.exists(path) else None


def compare_files(gen_path, ref_path, tolerance=TIMING_TOLERANCE, verbose=False):
    """Compare a generated events file against the metainformation reference.

    Returns a dict with comparison results.
    """
    gen_df = pd.read_csv(gen_path, sep="\t")
    ref_df = pd.read_csv(ref_path, sep="\t")

    result = {
        "generated": gen_path,
        "reference": ref_path,
        "status": "MATCH",
        "issues": [],
    }

    # 1. Row count
    if len(gen_df) != len(ref_df):
        result["status"] = "MISMATCH"
        result["issues"].append(
            f"Row count: generated={len(gen_df)}, reference={len(ref_df)}"
        )
        return result

    # 2. trial_id match
    if "trial_id" in gen_df.columns and "trial_id" in ref_df.columns:
        gen_ids = gen_df["trial_id"].astype(str).values
        ref_ids = ref_df["trial_id"].astype(str).values
        mismatches = sum(1 for a, b in zip(gen_ids, ref_ids) if a != b)
        if mismatches:
            result["status"] = "MISMATCH"
            result["issues"].append(f"trial_id: {mismatches} mismatches")

    # 3. Categorical columns (exact match)
    for col in ["word", "pairId", "mmmId", "trial_type"]:
        if col in gen_df.columns and col in ref_df.columns:
            gen_vals = gen_df[col].astype(str).values
            ref_vals = ref_df[col].astype(str).values
            mismatches = sum(1 for a, b in zip(gen_vals, ref_vals) if a != b)
            if mismatches:
                result["status"] = "MISMATCH"
                result["issues"].append(f"{col}: {mismatches} mismatches")
                if verbose:
                    for i, (a, b) in enumerate(zip(gen_vals, ref_vals)):
                        if a != b:
                            result["issues"].append(
                                f"  row {i}: gen='{a}' ref='{b}'"
                            )

    # 4. Timing columns (numeric tolerance)
    for gen_col, ref_col in [("onset_actual", "onset_actual"),
                              ("duration_actual", "duration_actual")]:
        if gen_col in gen_df.columns and ref_col in ref_df.columns:
            gen_vals = pd.to_numeric(gen_df[gen_col], errors="coerce")
            ref_vals = pd.to_numeric(ref_df[ref_col], errors="coerce")

            # Compare only where both are numeric
            both_valid = gen_vals.notna() & ref_vals.notna()
            if both_valid.any():
                diffs = (gen_vals[both_valid] - ref_vals[both_valid]).abs()
                max_diff = diffs.max()
                n_exceed = (diffs > tolerance).sum()

                if n_exceed > 0:
                    result["status"] = "MISMATCH"
                    result["issues"].append(
                        f"{gen_col}: {n_exceed} values exceed tolerance "
                        f"({tolerance}s), max_diff={max_diff:.6f}s"
                    )

    # 5. Response columns (exact match)
    for col in ["resp", "resp_RT"]:
        if col in gen_df.columns and col in ref_df.columns:
            gen_vals = gen_df[col].astype(str).values
            ref_vals = ref_df[col].astype(str).values
            mismatches = sum(1 for a, b in zip(gen_vals, ref_vals) if a != b)
            if mismatches:
                result["status"] = "MISMATCH"
                result["issues"].append(f"{col}: {mismatches} mismatches")

    # 6. Column set comparison
    gen_cols = set(gen_df.columns)
    ref_cols = set(ref_df.columns)
    extra = gen_cols - ref_cols
    missing = ref_cols - gen_cols
    if extra:
        result["issues"].append(f"Extra columns in generated: {sorted(extra)}")
    if missing:
        result["issues"].append(f"Missing columns vs reference: {sorted(missing)}")

    return result


def validate_subject(sub_num, tolerance=TIMING_TOLERANCE, verbose=False):
    """Validate all cued recall events for one subject."""
    results = []

    for cr_session in range(1, 16):
        # Encoding: 3 runs per session (sessions 1-14 only)
        if cr_session <= 14:
            for run in range(1, 4):
                gen = find_generated_file(sub_num, cr_session, "encoding", run)
                ref = find_metainfo_file(sub_num, cr_session, "encoding", run)
                if gen and ref:
                    r = compare_files(gen, ref, tolerance, verbose)
                    results.append(r)
                elif gen and not ref:
                    results.append({
                        "generated": gen,
                        "reference": None,
                        "status": "MISSING_REFERENCE",
                        "issues": ["No metainformation reference file found"],
                    })
                elif ref and not gen:
                    results.append({
                        "generated": None,
                        "reference": ref,
                        "status": "MISSING_GENERATED",
                        "issues": ["Generated file not found"],
                    })

        # Math: 1 run per session
        gen = find_generated_file(sub_num, cr_session, "math", 1)
        ref = find_metainfo_file(sub_num, cr_session, "math", 1)
        if gen and ref:
            r = compare_files(gen, ref, tolerance, verbose)
            results.append(r)
        elif gen and not ref:
            results.append({
                "generated": gen, "reference": None,
                "status": "MISSING_REFERENCE",
                "issues": ["No metainformation reference file found"],
            })

        # Retrieval: 4 runs per session (session 15: 2 runs)
        max_runs = 2 if cr_session == 15 else 4
        for run in range(1, max_runs + 1):
            gen = find_generated_file(sub_num, cr_session, "retrieval", run)
            ref = find_metainfo_file(sub_num, cr_session, "retrieval", run)
            if gen and ref:
                r = compare_files(gen, ref, tolerance, verbose)
                results.append(r)
            elif gen and not ref:
                results.append({
                    "generated": gen, "reference": None,
                    "status": "MISSING_REFERENCE",
                    "issues": ["No metainformation reference file found"],
                })

        # Recognition: outscan, 1 run per session
        gen = find_generated_file(sub_num, cr_session, "recognition", 1)
        ref = find_metainfo_file(sub_num, cr_session, "recognition", 1)
        if gen and ref:
            r = compare_files(gen, ref, tolerance, verbose)
            results.append(r)

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Validate generated cued recall events vs metainformation"
    )
    parser.add_argument("--subjects", default=None,
                        help="Comma-separated subject numbers (default: all)")
    parser.add_argument("--tolerance", type=float, default=TIMING_TOLERANCE,
                        help=f"Timing tolerance in seconds (default: {TIMING_TOLERANCE})")
    parser.add_argument("--verbose", action="store_true",
                        help="Show detailed mismatch info")
    args = parser.parse_args()

    if args.subjects:
        subjects = [int(s.replace("sub-", "").replace("sub_", ""))
                     for s in args.subjects.split(",")]
    else:
        subjects = SUBJECT_NUMS

    total_match = 0
    total_mismatch = 0
    total_missing_ref = 0
    total_missing_gen = 0

    for sub_num in subjects:
        print(f"\n{'='*60}")
        print(f"Validating {bids_sub(sub_num)}")
        print(f"{'='*60}")

        results = validate_subject(sub_num, args.tolerance, args.verbose)

        for r in results:
            status = r["status"]
            if status == "MATCH":
                total_match += 1
                if args.verbose:
                    print(f"  MATCH: {os.path.basename(r['generated'])}")
            elif status == "MISMATCH":
                total_mismatch += 1
                gen_name = os.path.basename(r["generated"]) if r["generated"] else "?"
                print(f"  MISMATCH: {gen_name}")
                for issue in r["issues"]:
                    print(f"    - {issue}")
            elif status == "MISSING_REFERENCE":
                total_missing_ref += 1
                if args.verbose:
                    gen_name = os.path.basename(r["generated"]) if r["generated"] else "?"
                    print(f"  MISSING_REF: {gen_name}")
            elif status == "MISSING_GENERATED":
                total_missing_gen += 1
                ref_name = os.path.basename(r["reference"]) if r["reference"] else "?"
                print(f"  MISSING_GEN: {ref_name}")

    print(f"\n{'='*60}")
    print("VALIDATION SUMMARY")
    print(f"{'='*60}")
    print(f"  MATCH:           {total_match}")
    print(f"  MISMATCH:        {total_mismatch}")
    print(f"  MISSING_REF:     {total_missing_ref}")
    print(f"  MISSING_GEN:     {total_missing_gen}")
    total = total_match + total_mismatch + total_missing_ref + total_missing_gen
    if total > 0:
        pct = 100 * total_match / total
        print(f"  Match rate:      {pct:.1f}% ({total_match}/{total})")

    return 0 if total_mismatch == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
