source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.10.2" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# Ruby 3.4 removes some stdlib gems from default; Jekyll requires csv
gem "csv"

# Ruby 3.4 also unbundles base64; safe_yaml indirectly requires it
gem "base64"

# Future-proof: logger will be removed from default in Ruby 3.5
gem "logger"
